/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FeeCollector } from "./FeeCollector";
export * as factories from "./factories";
export { FeeCollector__factory } from "./factories/FeeCollector__factory";
